channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.3.1
- pip:
  - mlflow
  - cloudpickle==2.2.0
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.2.0
  - typing-extensions==4.4.0
name: mlflow-env
